import type { DeviceTypeId } from "@/constants/deviceTypes";

/**
 * Suggested brands per device category for the device form dropdown.
 * Users can pick "Other…" and type any brand; stored value is always a plain string.
 */
export const DEVICE_TYPE_BRAND_OPTIONS: Record<DeviceTypeId, readonly string[]> = {
  switch: [
    "Cisco",
    "Aruba / HPE",
    "Juniper",
    "Ubiquiti",
    "Netgear",
    "TP-Link",
    "MikroTik",
    "Dell",
    "Extreme",
    "Arista",
  ],
  router: [
    "Cisco",
    "Ubiquiti",
    "MikroTik",
    "pfSense / Netgate",
    "SonicWall",
    "Fortinet",
    "WatchGuard",
    "Peplink",
    "Cradlepoint",
  ],
  access_point: [
    "Ubiquiti",
    "Aruba / HPE",
    "Cisco Meraki",
    "Ruckus",
    "TP-Link Omada",
    "EnGenius",
    "Grandstream",
    "OpenWrt / DIY",
  ],
  firewall: [
    "Fortinet",
    "Palo Alto",
    "SonicWall",
    "WatchGuard",
    "pfSense / Netgate",
    "Sophos",
    "Cisco ASA / FTD",
    "Check Point",
  ],
  server: [
    "Dell",
    "HPE",
    "Lenovo",
    "Supermicro",
    "Intel NUC",
    "ASUS",
    "Apple",
    "Custom / whitebox",
  ],
  server_backup: [
    "Dell (PowerProtect)",
    "HPE (StoreOnce)",
    "Unitrends",
    "Cohesity",
    "Rubrik",
    "Barracuda",
    "Quantum",
    "ExaGrid",
    "Synology",
    "QNAP",
    "IBM / Spectrum Protect",
    "OpenText",
    "Other appliance",
  ],
  power_supply: [
    "APC by Schneider",
    "Eaton",
    "Tripp Lite (Eaton)",
    "Vertiv",
    "Legrand / Raritan",
    "Server Technology",
    "CyberPower",
    "Panduit",
    "Geist (Vertiv)",
    "Enconnex",
    "Delta",
    "Generic / unlabeled",
  ],
  battery_backup: [
    "APC by Schneider",
    "Eaton",
    "Tripp Lite (Eaton)",
    "CyberPower",
    "Vertiv / Liebert",
    "Schneider Electric",
    "Minuteman",
    "Amazon Basics",
    "Other UPS",
  ],
  power_conditioner: [
    "WattBox + OvrC (Snap One)",
    "Furman",
    "Panamax",
    "SurgeX",
    "Torus Power",
    "Richard Gray's Power Company",
    "Middle Atlantic",
    "Tripp Lite",
    "APC / Line-R",
    "CyberPower",
    "Snap One (other)",
    "Monoprice Monolith",
    "Generic / unlabeled",
  ],
  dvr: [
    "Hikvision",
    "Dahua",
    "Axis",
    "Hanwha Vision (Wisenet)",
    "Bosch",
    "Digital Watchdog",
    "Uniview",
    "Avigilon",
    "Lorex",
    "Geovision",
    "LTS",
    "Other NVR/DVR",
  ],
  satellite_cable_tv: [
    "DIRECTV",
    "DISH",
    "Arris (CommScope)",
    "Technicolor",
    "Motorola",
    "Xfinity / Comcast",
    "Spectrum / Charter",
    "Verizon Fios",
    "Hughes",
    "Winegard",
    "TechniSat",
    "Generic set-top / modem",
  ],
  camera: [
    "Axis",
    "Hikvision",
    "Dahua",
    "Ubiquiti",
    "Reolink",
    "Arlo",
    "Google Nest",
    "Ring",
  ],
  printer: [
    "HP",
    "Canon",
    "Epson",
    "Brother",
    "Xerox",
    "Lexmark",
    "Ricoh",
    "Kyocera",
  ],
  patch_panel: [
    "Panduit",
    "Leviton",
    "Tripp Lite",
    "Black Box",
    "Monoprice",
    "Generic / unlabeled",
  ],
  other: ["Generic / unlabeled"],
};

export function getBrandOptionsForDeviceType(deviceTypeId: DeviceTypeId): readonly string[] {
  return DEVICE_TYPE_BRAND_OPTIONS[deviceTypeId] ?? DEVICE_TYPE_BRAND_OPTIONS.other;
}
